#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#cba6f7"
bspc config presel_feedback_color "#6272a4"

# follow mouse
bspc config focus_follows_pointer true

bspc rule -a system_monitor_scratchpad sticky=on state=floating rectangle=1000x600+183+84
